name: tr2d2-pep
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - rdkit
  - numpy
  - pandas
  - scikit-learn
  - jupyterlab
  - matplotlib-base
  - seaborn
  - tqdm
  - pyyaml
  - torchvision
  - pytorch-cuda=12.4
  - pip:
      - pytorch-lightning==2.5.5
      - lightning==2.5.5
      - fair-esm==2.0.0
      - transformers==4.56.2
      - SmilesPE==0.0.3
      - scipy==1.13.1
      - wandb==0.22.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - pathos==0.3.4
      - matplotlib==3.10.1
      - pandas==2.2.2
      - seaborn==0.13.2
      - timm==1.0.20
      - xgboost==3.0.5
      - loguru==0.7.3